services:
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server /data --console-address ":9001"
    ports:
      - "9000:${MINIO_API_PORT}"
      - "9001:${MINIO_WEBUI_PORT}"
    volumes:
      - .\data:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - .\postgres_data:/var/lib/postgresql/data

